version: 0.2

phases: 
  pre_build:
    commands:
      - cd reactimageviewer 
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - "**/**"
  discard-paths: no
  base-directory: reactimageviewer/build